name: nusa_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  another_flushbar: ^1.12.30
  auto_route: ^9.2.2
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_spinkit: ^5.2.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  intl: 0.19.0
  json_annotation: ^4.9.0
  loader_overlay: ^4.0.3
  logger: ^2.4.0
  shared_preferences: ^2.3.2
  sizer: ^3.0.4
  skeletonizer: ^1.4.2
  url_launcher: ^6.3.1
  faker: ^2.2.0
  iconsax_plus: ^1.0.0
  smooth_page_indicator: ^1.0.0
  google_generative_ai: ^0.4.7
  mime: ^2.0.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  camera: ^0.11.1
  flutter_markdown: ^0.7.7+1
  flutter_dotenv: ^5.2.1
  convert: ^3.1.2
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
  http: ^1.4.0
  flutter_svg: ^2.2.0
  page_transition: ^2.1.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  loading_animation_widget: ^1.3.0
  connectivity_plus: ^6.1.4
  geolocator: ^14.0.1
  permission_handler: ^11.3.1
  google_sign_in: ^6.3.0
  flutter_secure_storage: ^9.0.0
  googleapis_auth: ^1.4.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: ^5.0.0
  syncfusion_flutter_charts: ^29.1.38
  # flutter_document_picker: ^5.2.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/core/
    - assets/avatar/
    - assets/category/
    - assets/icons/
    - assets/images/
    - assets/images/onboarding/
    - assets/banner/
    - assets/firebase/
    