import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class InboxNotificationServices {
  static final _auth = FirebaseAuth.instance;
  static final _firestore = FirebaseFirestore.instance;

  static CollectionReference<Map<String, dynamic>> _userNotificationCollection(String uid) {
    return _firestore
        .collection('inbox_notification')
        .doc(uid)
        .collection('items');
  }

  /// ✅ Tambah atau update pesan selamat datang (1x per user)
  static Future<void> upsertWelcomeMessage() async {
    final user = _auth.currentUser;
    if (user == null) return;

    final uid = user.uid;
    final welcomeRef = _userNotificationCollection(uid).doc('welcome_message');

    await welcomeRef.set({
      'type': 'welcome',
      'title': 'Welcome to Nusa!',
      'message':
          "Welcome to Nusa! Get ready to explore Indonesia's traditions, heritage, and more — all generated by AI just for you.",
      'updateAt': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
  }

  /// ✅ Ambil semua notifikasi milik user saat ini
  static Future<List<Map<String, dynamic>>> getAllNotifications() async {
    final user = _auth.currentUser;
    if (user == null) return [];

    final snapshot =
        await _userNotificationCollection(user.uid).orderBy('updateAt', descending: true).get();

    return snapshot.docs.map((doc) => doc.data()).toList();
  }
}
