import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class InboxNotificationServices {
  static final _collection =
      FirebaseFirestore.instance.collection('inbox_notification');

  static Future<void> upsertWelcomeMessage() async {
    final user = FirebaseAuth.instance.currentUser;

    if (user == null) return;

    final userId = user.uid;

    await _collection.doc(userId).set({
      'title': 'Welcome to Nusa',
      'message':
          "Welcome to Nusa! get ready explore Indonesia's traditions, ,heritage, and more - alll generated by AI just for you.",
      'updateAt': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
  }

  static Future<Map<String, dynamic>?> getWelcomeMessage() async {
    final user = FirebaseAuth.instance.currentUser;

    if (user == null) return null;

    final doc = await _collection.doc(user.uid).get();
    return doc.exists ? doc.data() : null;
  }
}
